### ISSUE TITLE
Crash in MetadataQuery when search field that doesn't exist

### ISSUE THREAD

**Issue by clovis** [ARTFL-Project/PhiloLogic4#349]
If we try to search for something in a field that doesn't exist, we get a crash. Replicating is easy. Just search for anything in a non-existent field in the search form. Here's the traceback:

<pre><code>Traceback (most recent call last):
File "/var/www/html/philologic4/test/dispatcher.py", line 23, in philo_dispatcher
yield getattr(reports, report or "concordance")(environ,start_response)
File "/var/www/html/philologic4/test/reports/concordance.py", line 31, in concordance
concordance_object, hits = concordance_results(db, request, config)
File "/var/www/html/philologic4/test/reports/concordance.py", line 41, in concordance_results
hits = db.query(q["q"],q["method"],q["arg"],**q.metadata)
File "/usr/lib/python2.6/site-packages/philologic/DB.py", line 148, in query
corpus = MetadataQuery.metadata_query(self,corpus_file,metadata_dicts)
File "/usr/lib/python2.6/site-packages/philologic/MetadataQuery.py", line 19, in metadata_query
for corpus_obj in query:
File "/usr/lib/python2.6/site-packages/philologic/MetadataQuery.py", line 31, in query_recursive
r = query_lowlevel(db,param_dict)
File "/usr/lib/python2.6/site-packages/philologic/MetadataQuery.py", line 81, in query_lowlevel
results = db.dbh.execute(query,vars)
OperationalError: no such column: who</code></pre>

**Comment by clovis** [comment]
I believe this is now fixed with the way the HitList works now, right?
