### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by AlexandreGefen** [ARTFL-Project/PhiloLogic4#539]
On Ubuntu 16/Philologic 4.5 loading a big corpus fails in the middle :

```
parallels@ubuntu:~$ sudo philoload4 critique -c 2 -F /home/parallels/Desktop/listeTEIglobauxjanvier2017-parallels.txt The database folder could not be created at /var/www/html/philologic/critique
Do you want to delete this database? Yes/No
yes

Copying files to database directory... done.

### Parsing metadata ###
Tue Aug  8 16:54:18 2017: Parsing metadata in 1618 files...
Tue Aug  8 16:54:23 2017: Sorting files by the following metadata fields: ... 

### Parsing files ###
Traceback (most recent call last):
  File "/usr/local/bin/philoload4", line 30, in <module>
    l.parse_files(load_options.cores, load_metadata)
  File "/usr/local/lib/python2.7/dist-packages/philologic/Loader.py", line 310, in parse_files
    for n, x in enumerate(self.list_files())]
  File "/usr/lib/python2.7/genericpath.py", line 57, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: '1911_Vinet_Oeuvres_dAlexandre_Vinet_V_I-III_Etudes_sur_la_li_978_GALLICA.xml'
```

but the file does exist like the others in the middle of my list of 1618 files to load and is a valid xml file. Any idea ?

**Comment by AlexandreGefen** [comment]
PS problem confirmed with an another (big corpus) : loading stops in the middle (the file do exist).

```
parallels@ubuntu:~$ sudo philoload4 fabula -c 2 -F /home/parallels/Desktop/listeFabulaTEI-parallels.txt
The database folder could not be created at /var/www/html/philologic/fabula
Do you want to delete this database? Yes/No
yes

Copying files to database directory... done.

### Parsing metadata ###
Tue Aug  8 17:02:48 2017: Parsing metadata in 42895 files...
Tue Aug  8 17:03:56 2017: Sorting files by the following metadata fields: ... 

### Parsing files ###
Traceback (most recent call last):
  File "/usr/local/bin/philoload4", line 30, in <module>
    l.parse_files(load_options.cores, load_metadata)
  File "/usr/local/lib/python2.7/dist-packages/philologic/Loader.py", line 310, in parse_files
    for n, x in enumerate(self.list_files())]
  File "/usr/lib/python2.7/genericpath.py", line 57, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: '65137.xml'
```

**Comment by clovis** [comment]
You're actually not passing the database name in the right place, hence why you're getting the error:
`The database folder could not be created at /var/www/html/philologic/fabula`
You should first give the command line args, then the database name, and then the file path (in your case a text file containing file paths). Like so:
`philoload4 -c 2 -F fabula /home/parallels/Desktop/listeFabulaTEI-parallels.txt`

**Comment by AlexandreGefen** [comment]
Same mistake on Ubuntu and Mac :

```
MacBook-Pro-13-de-Alexandre:PhiloLogic4.5 alexandregefen$ sudo philoload4 -c 4 -F critique /Users/alexandregefen/Documents/DH/Outils/listeTEIglobauxjanvier2017.txt

Copying files to database directory... done.

### Parsing metadata ###
Thu Aug 10 09:41:52 2017: Parsing metadata in 1618 files...
Thu Aug 10 09:41:56 2017: Sorting files by the following metadata fields: ... 

### Parsing files ###
Traceback (most recent call last):
  File "/usr/local/bin/philoload4", line 30, in <module>
    l.parse_files(load_options.cores, load_metadata)
  File "/Library/Python/2.7/site-packages/philologic/Loader.py", line 310, in parse_files
    for n, x in enumerate(self.list_files())]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/genericpath.py", line 57, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: '1900_Maurice_Barres_H_Taine_sa_vie_et_sa_correspondance_56_OBVIL.xml'
```

But there is a file "1900_Maurice_Barres_H_Taine_sa_vie_et_sa_correspondance_56_OBVIL.xml" correctly copied in the /data/text/ folder

**Comment by clovis** [comment]
Were you ever able to solve this issue? I have not seen this problem ever occur on our systems.

**Comment by clovis** [comment]
Sorry for never getting back to you on this. Have you tried a newer release of PhiloLogic4?

**Comment by clovis** [comment]
Closing because no new comments.
